<table>
<tr><td>
<?php if(!$this->form->getValue('CacheForm')) echo $this->form ; ?>
</td></tr>
<tr><td>
	<table>
    <tr>
        <th>Indicatif présent</th>
        <th>Indicatif imparfait</th>
        <th>Passé simple</th>
        <th>Futur simple</th>
        <th>Conditionnel Présent</th>
        <th>Subjonctif présent</th>
        <th>Participe présent</th>
        <th>Infinitif présent</th>
    </tr>  
    <tr>
        <td>
        	<table>
        		<tr>
        			<td><?php if ($this->form->getValue('elision')==1) echo "J'"; else echo "Je" ; ?></td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[0]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Tu</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[1]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Il/Elle</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[2]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Nous</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[3]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Vous</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[4]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Ils/Elles</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[5]['lib']; ?></td>
        		</tr>
        	</table>
        </td>
        <td>
        	<table>
        		<tr>
        			<td><?php if ($this->form->getValue('elision')==1) echo "J'"; else echo "Je" ; ?></td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[6]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Tu</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[7]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Il/Elle</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[8]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Nous</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[9]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Vous</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[10]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Ils/Elles</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[11]['lib']; ?></td>
        		</tr>
        	</table>
        </td>
        <td>
        	<table>
        		<tr>
        			<td><?php if ($this->form->getValue('elision')==1) echo "J'"; else echo "Je" ; ?></td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[12]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Tu</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[13]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Il/Elle</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[14]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Nous</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[15]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Vous</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[16]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Ils/Elles</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[17]['lib']; ?></td>
        		</tr>
        	</table>
        </td>
        <td>
        	<table>
        		<tr>
        			<td><?php if ($this->form->getValue('elision')==1) echo "J'"; else echo "Je" ; ?></td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[18]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Tu</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[19]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Il/Elle</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[20]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Nous</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[21]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Vous</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[22]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Ils/Elles</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[23]['lib']; ?></td>
        		</tr>
        	</table>
        </td>
        <td>
        	<table>
        		<tr>
        			<td><?php if ($this->form->getValue('elision')==1) echo "J'"; else echo "Je" ; ?></td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[24]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Tu</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[25]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Il/Elle</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[26]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Nous</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[27]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Vous</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[28]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Ils/Elles</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[29]['lib']; ?></td>
        		</tr>
        	</table>
        </td>
        <td>
        	<table>
        		<tr>
        			<td><?php if ($this->form->getValue('elision')==1) echo "J'"; else echo "Je" ; ?></td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[30]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Tu</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[31]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Il/Elle</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[32]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Nous</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[33]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Vous</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[34]['lib']; ?></td>
        		</tr>
        		<tr>
        			<td>Ils/Elles</td>
        			<td><?php echo $this->form->getValue('prefix').$this->Terms[35]['lib']; ?></td>
        		</tr>
        	</table>
        </td>
        <td><?php echo $this->form->getValue('prefix').$this->Terms[36]['lib']; ?></td>
        <td><?php echo $this->form->getValue('prefix').$this->Terms[37]['lib']; ?></td>
    </tr>  
	</table>
</td></tr>
</table>