<p>Êtes-vous sûr de vouloir supprimer ?</p>
<form action="<?php echo $this->url(array('action'=>'supprimer')); ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
    <input type="hidden" name="idParent" value="<?php echo $this->idParent; ?>" />
    <input type="submit" name="supprimer" value="Oui" />
    <input type="submit" name="supprimer" value="Non" />
</div>
</form>
